function V = RLC_DE_sin(t,Y,R,L,C,fin)
%RLC_DE_SIN
%    V = RLC_DE_SIN(T,Y,R,L,C,FIN)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    12-Dec-2020 10:36:33

t2 = Y(2);
V = [t2;-(-sin(fin.*t.*pi.*2.0)+Y(1)+C.*R.*t2)./(C.*L)];
